<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JSSP.Core\JSSP.Core.csproj" />
    <ProjectReference Include="..\JSSP.IO\JSSP.IO.csproj" />
    <ProjectReference Include="..\JSSP.Algorithms\JSSP.Algorithms.csproj" />
    <ProjectReference Include="..\JSSP.UI\JSSP.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Terminal.Gui" Version="2.0.0" />
  </ItemGroup>

</Project>
